### ISSUE TITLE
test assues that -N is an allowed option to mpirun

### ISSUE THREAD

**Issue by rhaas80** [ECP-VeloC/shuffile#11]
In

https://github.com/ECP-VeloC/shuffile/blob/ce47d6c65052081c2885adfd4733897ec1f5f8f8/test/CMakeLists.txt#L11

the test assume that

```
${MPIEXEC} -n6 -N3 -m block ./shuffile_test
```

is generically valid, however -N is not a documented option of mpiexec and seems to mostly be an srun or so option to specify how many ranks per node to use. It fails eg if RESOURCE_MANAGER=NONE is used and OpenMPI is the mpi stack.

**Comment by rhaas80** [comment]
It should also use `${MPIEXEC_NUMPROC_FLAG} 6` ie a variable for the `-n` option name and a space in between option and value. I have no clue what `-m block` does or if it is required for the test (I can see that `-N`, the number of MPI ranks per node should matter).

**Comment by CamStan** [comment]
Looks like this was fixed with the addition of `SHUFFILE_ADD_TEST()` in #9.
